package com.breckneck.deptbook.domain.util

const val ROTATE_DEGREE_DEBT_IMAGE_VIEW_BY_INCREASE = 180f
const val ROTATE_DEGREE_DEBT_IMAGE_VIEW_BY_DECREASE = 0f

const val ROTATE_DEGREE_HUMAN_IMAGE_VIEW_BY_INCREASE = 180f
const val ROTATE_DEGREE_HUMAN_IMAGE_VIEW_BY_DECREASE = 0f

const val DEBT_QUANTITY_FOR_LAST_SHOW_APP_RATE_DIALOG = 35
const val DEBT_QUANTITY_FOR_NEXT_SHOW = 10
