package com.breckneck.debtbook.core.ui.theme

import androidx.compose.ui.graphics.Color

// M3 neutral palette — monochrome B&W design with minimal chroma.
// Preserves the app's signature black/white identity in M3 token structure.

// region Light scheme
val md_theme_light_primary = Color(0xFF2E2E31)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0E3)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1A1D)
val md_theme_light_secondary = Color(0xFF5C5C5F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1E0E4)
val md_theme_light_onSecondaryContainer = Color(0xFF191A1D)
val md_theme_light_tertiary = Color(0xFF5C5C5F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE1E0E4)
val md_theme_light_onTertiaryContainer = Color(0xFF191A1D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFC)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFCFCFC)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE4E1E6)
val md_theme_light_onSurfaceVariant = Color(0xFF47464A)
val md_theme_light_outline = Color(0xFF78767A)
val md_theme_light_outlineVariant = Color(0xFFC8C5CA)
val md_theme_light_inverseSurface = Color(0xFF313034)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFFC7C5CA)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF6F2F7)
val md_theme_light_surfaceContainer = Color(0xFFF0ECF1)
val md_theme_light_surfaceContainerHigh = Color(0xFFEAE7EC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE5E1E6)
// endregion

// region Dark scheme
val md_theme_dark_primary = Color(0xFFC7C5CA)
val md_theme_dark_onPrimary = Color(0xFF303033)
val md_theme_dark_primaryContainer = Color(0xFF464649)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3E2E6)
val md_theme_dark_secondary = Color(0xFFC6C5C9)
val md_theme_dark_onSecondary = Color(0xFF2E2F32)
val md_theme_dark_secondaryContainer = Color(0xFF454548)
val md_theme_dark_onSecondaryContainer = Color(0xFFE2E1E5)
val md_theme_dark_tertiary = Color(0xFFC6C5C9)
val md_theme_dark_onTertiary = Color(0xFF2E2F32)
val md_theme_dark_tertiaryContainer = Color(0xFF454548)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2E1E5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF47464A)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5CA)
val md_theme_dark_outline = Color(0xFF928F94)
val md_theme_dark_outlineVariant = Color(0xFF47464A)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF313034)
val md_theme_dark_inversePrimary = Color(0xFF5E5E62)
val md_theme_dark_surfaceContainerLowest = Color(0xFF110F14)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1B1E)
val md_theme_dark_surfaceContainer = Color(0xFF211F24)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2B292E)
val md_theme_dark_surfaceContainerHighest = Color(0xFF363439)
// endregion

// App-specific semantic colors
val Green = Color(0xFF59CB72)
val Red = Color(0xFFE25D56)
val Yellow = Color(0xFFE4CB23)
